name: Bug Report
description: Create a report to help us improve. On the next screen, please fill in the template provided in the post description.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
       Please fill out the following details to submit a bug report:
  - type: textarea
    id: what-happened
    attributes:
      label: Problem Description
      description: Please describe your problem in as much detail as possible. Include any steps necessary to reproduce the problem. You can also include screenshots if desired. 
    validations:
      required: true
  - type: textarea
    id: activity-log
    attributes:
      label: Activity Log, Crash Log or any other details
      description: An Activity Log is required for support. Please read https://handbrake.fr/docs/en/latest/help/activity-log.html for more information.
      render: text
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What Operating System are you running?
      placeholder: e.g. Windows 10, macOS 11, Ubuntu 20.04
    validations:
      required: true
  - type: input
    id: hb-version
    attributes:
      label: What version of HandBrake are you running?
      placeholder: e.g. 1.3.3, Nightly 10c4c78
    validations:
      required: true
  - type: input
    id: hb-download
    attributes:
      label: Where did you download HandBrake from?
      placeholder: e.g. handbrake.fr, github, flathub etc.
    validations:
      required: false



